### ISSUE TITLE
24 wallets with airdrop hunter

### ISSUE THREAD

**Issue by jjjvvvbb** [safe-global/safe-user-allocation-reports#112]
# Related Safe Addresses

0x06f328725c02888df24385aaabc5fa1fea619394 
0xda43394f4c403df53e95865b1a2659039ecdb2a2 
0xf2b7195805e7c1e66775d811ebc02d9b83ab54e5 
0x8ac00ae8db651c46a7e35263ef0e4350b22ffe68    
0xf4f31dae77842165fef83abdc902337dad6169e0    
0xd6251a28d17b53c4d59ee85fceef992ca3420c9e   
0xe6f0f92e0a0b672fa7293a89f70baa6bcf77d087  
0xef7a277dc145410084ed9a31f7b20437298e8bd4   
0x69482418ded8ba0b2b2f3fdb93210895497f13e7
0x728708ed43821fc8abf4f94d0b8bf98325923355   
0x5c017dcedd52743b86711fd8bf39f4bc43393954   
0x716c65a6f1d6bdc17ec2bbfc2801466885b69010   
0x1cfbbfc0a2a4bfcece1e7a0cad2647c1d99a1fdd    
0x770e1d9628e722f9c101fe63f2c5fa87b6433805    
0x79b5278867e3d33229fd7956a29b6371219c7e9c    
0xe7f5320c28212a74a2ab038fec940716d71ddaf2    
0x727c7f0488ddbd0b520be2a3c3a9b1ccf993d2f3      
0x7b03ED7c2c748E19DA0B455E2B96Ebf189e00208     
0x24161ECeA12F4c0535393e958Ef5a186776bab0e         
0x06F8345Ea88dB23858cD1d4c585efcfA65CD5dfe       
0x593FC161559405253d9b80D0462f0fAd2272fAD2        
0x4a6fB0f864313BBc5303A006516b3C0299f3332d          
0x4E020272C031121d7bcF6b2eEfDc34AEd1b611Ce         
0x7eF74555c44d103710a2Df9554D61BfbD14A4Be7    

# Reasoning

initial account:  0xed6fd1c824c7269e1f493fb9ad802f049b67760f   this account creat 9 safe wallets then send eth to 0xa6e087A55837f10B6C01480991C70f62D42C585C ,  then use second address create  15 safe wallets. it is clear that this guys is airdrop hunter.  All safe addresses are just for airdrop and no more transcation. Same amount of tokens from these accounts.

# Methodology

just discovered by etherscan and excel , it is so clearly for this airdrop hunter.

# Safe Address

0x4c4682F81A95F6D76444e3ea20753AD5B7d643b4

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
