### ISSUE TITLE
0x00feb309c5d8b423b50fab39bfffac9cb5fca50a airdrop farmer

### ISSUE THREAD

**Issue by dcswaporg** [safe-global/safe-user-allocation-reports#113]
# Related Safe Addresses
0x00feb309c5d8b423b50fab39bfffac9cb5fca50a
0x52b87a21a4aaa1e1fb2a1d6709ff8192137b0dfa
0x99F3bbc0766d93ee8D28cE4A11C98f49e05af74c
0x6E91D2D3052C4BBD33fEa7Ebd487CA79C6e99d6C
0xcB1c3b015f5F2A9256ef5773abbD4eA47fC019E9
0x6269ac49731125fc6ea71698720eaa4d10cacc12
0x1227da57a9ceabafe227d621610a19a3472bf4f7
0xab975481541841367185affd8638424a2f0bc59c
0x718d79d02d9dd30f52d9b659a5541811417a2824
0x926f4b6637db95837af8ebff4e3fd7fbd926b39c
0x718d79d02d9dd30f52d9b659a5541811417a2824
0x926F4b6637Db95837Af8ebff4e3fD7FBd926B39C
0x5135ef87a0c6b3acf36e3c4784c7ce16434910a0
0x23416ccc0e32ba401adf34f4da7db4ad4040f1e5
0x4283bff1e9caa42629b39d2d452978f1c688aae4
0xaae7cBDDf5eFfAd91Aeb081fcC51827B047d95C0
and more

# Reasoning
The first address 0x00feb309c5d8b423b50fab39bfffac9cb5fca50a transfers gas fees to  0x52b87a21a4aaa1e1fb2a1d6709ff8192137b0dfa, and the 0x52b87a21a4aaa1e1fb2a1d6709ff8192137b0dfa transfers gas fees to  all below all the below address.

# Methodology
you can find detail here:
https://etherscan.io/address/0x52b87a21a4aaa1e1fb2a1d6709ff8192137b0dfa#internaltx

# Safe Address
0x00feb309c5d8b423b50fab39bfffac9cb5fca50a

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
