### ISSUE TITLE
report 

### ISSUE THREAD

**Issue by buihoangthai** [safe-global/safe-user-allocation-reports#118]
# Related Safe Addresses
```
0x98157939ed669fd05ed457029b8b6ac33597772f ( contract creator lenovogroup.eth)
0x7be578d6b3fcb64d0a9123cc104746b0d2ed6051  ( contract creator tugege.eth )
0x94569fc153906f79f4bbb1c9100f2e57230ff86f  ( contract creator 0xbbfc1d1f420703aebe13007f5ce0182f70bf35b9 ) 
0x98157939ed669fd05ed457029b8b6ac33597772f ( contract creator lenovogroup.eth ) 
---------------------------------------------------------------------------------------------------------------------------------
( contract creator 0x5769770F5EFe8fB017FB09B6dE3B2d096668377D at txn ....) 
0x00044c87ddc54536ee05047c6f4f6f831aba988b 
0x74faeded6221c9f184139817a724ceab2391d9ca 
0x7b7a5725602ff0f475dc7f1997b0862d1a7fe096 
0xe5c4e7204a2374f6f394ffda118dcba5f5378f6b 
0x3ea23355ecdcfda257fae663c78c8a556ce5581b 
0x4AB366bb8bC710C222B57BD2803806F3e53a5421 
0x782cd5782852Da009e3422dD1b34379E62C2aa23 
0xBdbC2721254dD29b8638871108B1e5Af358EF641 
0xBf374F68c519173816d96Ad6368839B3824c9BC7 
0xd5c69f32978906Ae3F1a44E2e242b38Cc0849A05
0xf06A1Fe01a19B83E6E323e4a977ed4cC12f7F677
0xFaF987B0989eFD38086fCc4525F1D97686D61406
-----------------------------------------------------------------------------------------------------------------------------------
```
# Reasoning 
 - The first 4 addresses is one person created 4 multi-signatures , all send 0.01 ETH at the same time apart ( Jul-27-2022 08:59:22 AM +UTC)  48days 8h ago then deposit eth in compound . All wallets contract creators have all been transferred one or more times from an ENS named tugege.eth and have compatible txns (using identical protocols like swap on metamask ....) probably for airdrop farming . 
- Next 12 addresses one person and one address created 12 multi-signatures ( https://etherscan.io/tx/0x2dd72dfebf437eb980581ae7cc0c54756647129b5daa84055ebd61d326bca240#eventlog ) . All received the same $SAFE is 155.39155332697567
# Methodology
I initially found out which addresses were distributed with the same $SAFE number , then went to ethscan.io and searched for txn , pretty simple

# Safe Address
0x5b5f8033C080E454d54274380EB1DEc1d36c40C5

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
