### ISSUE TITLE
13 safes were created by an airdrop farmer

### ISSUE THREAD

**Issue by Finelorrew** [safe-global/safe-user-allocation-reports#150]
# Related Safe Addresses

13 safes were created by an airdrop farmer
0x155bdbdaac9bba68c62199b5f912d53ef74ec563
0x6161ef0ce79322082a51b34def2bcd0b0b8062d9
0x5846f9a299e78b78b9e4104b5a10e3915a0fae3d
0x7927b537e171b33bc11d30191cae18357817efb5
0x390c26b5cb56269dab8c8dce693714560d713143
0x17bc2c070464ab64206c4001450b1503e2503a0a
0xd1a4b3f7762b01a64f9149eac1b28e8ef9c61d9b
0x4fc50236af16f9642ec6b1f56ecbdf8398ec76dd
0xa31f46140fe7b115f3e2e871a96e9e938f69ebe3
0x61a00471e4277d63fa006de87f66ed76fe7e15a0
0x7e90a8488b3e2ae9807e80c00fee84c5c7ad6666
0xfe9df826ed3beee9b7ed91f8deaf152db19c2af3
0x9e8758f2c9faa3297a1f530c70ec753a5975883f

# Reasoning
<just discovered by excel and etherscan , it is so clearly for this airdrop  #hunter..>

# Methodology

After executing luabase found,Above 13 addresses All created by 0xe89574779879aD47b5bdCd4F62063b0cEa9A42F5
There are many related transactions between addresses..

# Safe Address

(eth:0x9b2Fb6224bBB0492bEa27dd9A7130363C5B8840A)

**Comment by tschubotz** [comment]
Creating multiple Safes from the same account is not airdrop farming per se. e.g. when wallets use a relayer, that will be creator of all wallets. Please elaborate on why you think this is airdrop farming.

**Comment by Finelorrew** [comment]
> Creating multiple Safes from the same account is not airdrop farming per se. e.g. when wallets use a relayer, that will be creator of all wallets. Please elaborate on why you think this is airdrop farming.
the less cost for hunters take.

**Comment by Finelorrew** [comment]
with target as (
select *
from url('https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/safe_user_allocations_reworked.csv', CSVWithNames)
), transactions as (
select t1.*
from ethereum.transactions t1
join target t2
on t1.to_address = t2.safe_address
)

select distinct to_address
from transactions
where from_address = lower('0xe89574779879aD47b5bdCd4F62063b0cEa9A42F5')

**Comment by Finelorrew** [comment]
This is not a relayer

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
