### ISSUE TITLE
22 safes were created by an airdrop farmer

### ISSUE THREAD

**Issue by jemoker** [safe-global/safe-user-allocation-reports#153]
# Related Safe Addresses

0x43e186b7af9a152f11392c82b3b57a79161f9168
0xb5099ee9a42a7add0afe389bfbcd6c40c5a147c4
0xbad6fcb58ade50d0fac679b99193a00c452b3f5c
0x2db377add47f5d1a321a634d5d10e0524cd939ba
0x0394626f556f772d67c928bb42760c091ff60804
0x4e748d6b60cd5c83859acf63189669bc83044fa6
0x7445c64684ba17aaf03b17fc39b208ee67c47eb3
0xaeb53bd66935133b2c4a32241d663f60af8ef5c6
0x51217e4769dfd61a42f8a509d4dccc5683bfcb21
0x1bf43eb884a0624989f99ed4ac3f1a2bde0152f5
0x81c89274dc7c9bace082d2ca00697d2d2857d2ee
0x3c7a1158d85b264cc8cdc715a6fe8d408b5f6129
0x4f1e062427302410a84a48c45c07834cb9960359
0x6c76e2d26ac3010dbe081481698724030aedbe0b
0x2f1098c021b96e740f291c2d9d7a9562b2f7539a
0xa232ec1090723b860cbed25480214c9e4607f002
0xbd40d7e895b87b8ff6a3f3203256a8e2003b79f2
0x1db4597389199f8851b53ed48ae90bf451c564fe
0x575d09e5149f778178da52edebe06d326def24da
0xb1339aa0b62a49ceb555a54af358fd1f31ed6814
0x1cc2670592a99716e3ae3e6d8132e8b2f924d457
0x002184c787c58638d41d7b6f35b38b2a967e5033

# Reasoning
The airdrop farmer used the 0x2e173510024d480d195d8875e4d55e9b6198b654 mainnet wallet to create 22 wallets

# Methodology
all address is create by this transaction: https://etherscan.io/tx/0xb2934be81195c1d56385856ad0e6319670b6b6fa4ca0c766404f562e082a57a1#eventlog

# Safe Address
0x90D1e4780D0B1422c2AD1a3Ae274d08e1c99Ecc0

**Comment by tschubotz** [comment]
Creating multiple Safes from the same account is not airdrop farming per se. e.g. when wallets use a relayer, that will be creator of all wallets. Please elaborate on why you think this is airdrop farming.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
