### ISSUE TITLE
19 related safe address

### ISSUE THREAD

**Issue by deshawelafi** [safe-global/safe-user-allocation-reports#165]
# Related Safe Addresses

```
0x6e48eb8b629725110d86641253a7b9e1f01b3acd
0xd004e03bb12b4422bc3e02ce315c65dc9d82cd49
0xc8c5899103a0803a95da06e4ab44219d3b56a834
0x724e08c98256a570aadbac6d20c1b9ccce208f28
0x88b8de7234376a22a5f23b9a33ae3a97bba564de
0xdbb24dff1aaad61f5fffe17b85153156d6e567b5
0x4605db3c81fbae12905eba1196da819b56f24f16
0x4651b4a07f645a1030a73675071697033fc4cbee
0x79bdd2c976685f500a6e0f601b496acff20b56a7
0xf57843d682c1fc9c04c11f239812939043e28f0b
0xef268658776cf63e2d4e732da6cde8f87735de7f
0x379f4da45b98c4ccb95e961cf2acbf0138513095
0x7c21891e44093d5ebb8f6fd8c4d8b7ee38c64b24
0x408cce46cb8813ffe7a17cbca845be19e23fb9ee
0x9e497b978a44f8c3e5f3458090b3d532fe128df1
0xac3232fed5d1a770b8defdf6d2143157fae59bec
0x54f5d2be819a3d11163a46d57fa1f3176458b1a5
0x2c9fc543242ccf46487204fcbca904353ecdd10d
0x1cbbddd354811fe652b6c9b36506bb171dd7cf6b
```
-->

# Reasoning

These 19 safes were all created by 0xf50cc7bae4af42c94d2cf865309bded1203f029f
After setup, each safe receives 14999 and 1 GRT via two transfers .

# Methodology

List of addresses via airdrop
https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/safe_user_allocations_reworked.csv
Compare with the creation address and the safe-drop address of the created safe-drop, extract the duplicate created addresses, and perform manual analysis whether the behavior of each safe-drop address has a certain meaning or suspected airdrop hunters.

# Safe Address

0x8A53e15783D003F93ED1dD376EA157b8E304d35A

**Comment by deshawelafi** [comment]
Tool description.
https://sdk.flipsidecrypto.xyz/shroomdk was used to get the address to create the safe

SQL_QUERY = """
    SELECT 
         TX_FROM_ADDRESS,EVENT_INPUTS['proxy']
    FROM ethereum.events_emitted 
    WHERE
    tx_to_address = '0xa6b71e26c5e0845f74c812102ca7114b6a896ab2'
    ORDER BY block_timestamp asc
    LIMIT 100000
"""

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
