### ISSUE TITLE
All these addresses are created in one tx and have similar behaviors. They are not normal user.

### ISSUE THREAD

**Issue by mmyyrroonn** [safe-global/safe-user-allocation-reports#208]
# Related Safe Addresses

```
0x00b5c3dcf3e07cdb0a61af9eb631a94d4f23a92c
0xc646aa2351ff531bfe3cbe779e730b084287d6b8
0x5c40baec05d9493ed1f45c1022b2a0ce81624adf
0xab65c89e88946bde7d8e2f647e23c2011373c65a
0x9167835b05c547938925244a061def72ec0c5d5a
0x8203f5d6370e7e36d383fcaee5d9a477cf083dca
0xa24009391181cf02f2c0c1338a03b2d85b9643dd
0x401d72cef658c2347fb61e0298ab364165e57a25
0x40a72e6628754b0f4945118cfe195a14ba2cf484
```

# Reasoning

All above addresses are created by one address in one tx through a contract. Meanwhile, the behavior of them is quite similar. Some of them just created a contract and did nothing, such as 0x40a72e6628754b0f4945118cfe195a14ba2cf484, 0xa24009391181cf02f2c0c1338a03b2d85b9643dd, 0xab65c89e88946bde7d8e2f647e23c2011373c65a
# Methodology

I just pick up an address and analysis. You can check this etherscan link to verify.
https://etherscan.io/tx/0x1de8d2806d3e37f29e34b5fbdc590f8b4f19484c4b3ef51004587d2d3e6b3d57#internal

# Safe Address

0x0c392925C0ae6EBd549a9bDbeE6f1DdC98626A0b

**Comment by tschubotz** [comment]
> # Reasoning
> All above addresses are created by one address in one tx through a contract. Meanwhile, the behavior of them is quite similar. Some of them just created a contract and did nothing, such as 0x40a72e6628754b0f4945118cfe195a14ba2cf484, 0xa24009391181cf02f2c0c1338a03b2d85b9643dd, 0xab65c89e88946bde7d8e2f647e23c2011373c65a

This reasoning is not sufficient. I checked the [first Safe](https://gnosis-safe.io/app/eth:0x00b5c3dcf3e07cdb0a61af9eb631a94d4f23a92c/transactions/history). It has more txs. How do you argue that this is no legitimate use? 



> the behavior of them is quite similar

Why don't you just explain what the behavior is?

> Some of them just created a contract and did nothing

So which one did "nothin" and which ones did more? Please don't wait for us to do the investigation work.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
