### ISSUE TITLE
has same creator from 0x5c886B3Ed9fb762f1eB55EB98c00df4D3cF63322

### ISSUE THREAD

**Issue by ExRui** [safe-global/safe-user-allocation-reports#230]
# Related Safe Addresses

```
0x1c97057713C2C56599f694A920b060f1da5D94A7
0x2A0E02dd94c2b34ba8f94eB00807A3ABa34e62cD
0x364Ad04e974A7CbCbA5C07A867edafff5Dd12586
0x47628ad01892a06cA574e45dfe8Bfb69a1cB1971
0x5a80263780898C6AF01A6d57FA717aB8E3640bc3
0xc31997f8e495a51E3D2346674d0Edb6804dEc1D3
0xc8E1275babc318721EAa73a6c1281fca5257F0B5
0xd07C67bDf9454B6Ea26b2f5E1160A5EEE1b0f299
0xda43a32F07A41B0e1b6b53a62B593C577c65C81a
0xe31F1C4e3B9699b971b7D4e7a8FC4eF0E39a70F9
```

# Reasoning
Those Safe Vault has same creator from 0x5c886B3Ed9fb762f1eB55EB98c00df4D3cF63322

# Methodology
I check the safe vault who has same tokens and same creator, Then manually detect if they were created by the same person.

# Safe Address
0x88A253aD0be9081b6D520B91a7e620eDd6Ad5c7b

**Comment by tschubotz** [comment]
> # Reasoning
> Those Safe Vault has same creator from 0x5c886B3Ed9fb762f1eB55EB98c00df4D3cF63322

Creating multiple Safes from the Safes is not airdrop farming per se.

Please elaborate on why you think this is in fact airdrop farming.

**Comment by ExRui** [comment]
> > # Reasoning
> > Those Safe Vault has same creator from 0x5c886B3Ed9fb762f1eB55EB98c00df4D3cF63322
> 
> Creating multiple Safes from the same account is not airdrop farming per se. Could be a relayer or individual/project using multiple Safes for various reasons.
> 
> Please elaborate on why you think this is in fact airdrop farming.

these vaults has same tx from
https://etherscan.io/tx/0x383e323e1e16164e08003f1c80db6862e862f0c665698384c66b382e92cf617b
and
https://etherscan.io/tx/0x15c52eca58ac3c9409587005c0a38db01ffe34556c3535f688fe56e79cd7398e

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
