### ISSUE TITLE
has same creator from 0x2e173510024d480D195d8875E4D55E9b6198b654

### ISSUE THREAD

**Issue by ExRui** [safe-global/safe-user-allocation-reports#232]
# Related Safe Addresses

```
0x0e985261973434b417fedd7b3edcc52dedeb1745
0x53f57fc3ce4940e68c990ee7c16df12576f4161a
0x6686490145598bbb3943d460fe85ff4fe3158bc0
0x6708a2d0a0be40935e95609142e75d0482fb77af
0x813b9d9f2e5f6c987922b115ac022d0a8a2c0cc9
0x8fe0ce0159553e2fb7e7a5b6915137d11e11bf2c
0xa79b0d902cf20d8e31ed3cf14c5a00b2d71f9ab9
0xbe3b1a11194f09cd471bb4ab620807ef58ca4198
0xe078a303df0dfda45709bb1a8c56577664e65e51
0xe166ffb494b17f3c7f6d83810bb7163507548cf9
```
-->

# Reasoning
Those Safe Vault has same creator from 0x2e173510024d480D195d8875E4D55E9b6198b654

# Methodology
I check the safe vault who has same tokens and same creator, Then manually detect if they were created by the same person.

# Safe Address
0x88A253aD0be9081b6D520B91a7e620eDd6Ad5c7b

**Comment by tschubotz** [comment]
> # Reasoning
> Those Safe Vault has same creator from 0x2e173510024d480D195d8875E4D55E9b6198b654

Creating multiple Safes from the same account is not airdrop farming per se. Could be a relayer or individual/project using multiple Safes for various reasons.

Please elaborate on why you think this is in fact airdrop farming.

**Comment by ExRui** [comment]
> 0xe166ffb494b17f3c7f6d83810bb7163507548cf9



> > # Reasoning
> > Those Safe Vault has same creator from 0x2e173510024d480D195d8875E4D55E9b6198b654
> 
> Creating multiple Safes from the same account is not airdrop farming per se. Could be a relayer or individual/project using multiple Safes for various reasons.
> 
> Please elaborate on why you think this is in fact airdrop farming.

these vaults has same tx from https://etherscan.io/tx/0xe5745cdfd7073dec63322083f6e38e01498629576b808435bdf4506e68293112
and
https://etherscan.io/tx/0x2b6d5c9667d8eea5a0afe5bce8f35676b0c8542514717f2e0f1eae8da9d389ef
https://etherscan.io/tx/0x9d54b6a95c8ee85e90afe94ab0c41fbbfca86df1cb3ac4ace97c5be0a8fc09e4

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
