### ISSUE TITLE
has same owner from 0x2A1049062c6Cfd69bd38fbaf3b0559DF1DBbc92c 0x02CA4101eA84f400c62b3BeB87Fb5450a8702941

### ISSUE THREAD

**Issue by ExRui** [safe-global/safe-user-allocation-reports#241]
# Related Safe Addresses

```
0xd2749489a4b7c3754f83bad20eb8bef5ab61bdbb
0xd3ae95bbd12fc31335ce5f884b1782bd7251edd7
0xeed778bc497ac8f8104a54f3ae2116a9aa27594e
0xfa709bf66d44526302a53821b5126746a45ba82a
0x8CA6fb6A34dA6B5f486f977c5E1c7eB021233625
0x54d2f913348f79bbddcd62d4eedc8f39fe851654
0x58d0c3df11c938aca49b4ba7ceeedc8abda066d1
0x668b9bd7c09f448dc94a883863e7115f84fa529c
0xa15f1754d25a5e97028323b56ba8bea5c48a8e6a
0xa40320e6495ec554645746af3e36209a0e08871d
0xc1906daafdd4b782221db9250ab36242d8229b76
```
-->

# Reasoning
Those Vault has same owner by 0x8CA6fb6A34dA6B5f486f977c5E1c7eB021233625 .
And same creator from 0x2A1049062c6Cfd69bd38fbaf3b0559DF1DBbc92c 0x02CA4101eA84f400c62b3BeB87Fb5450a8702941

# Methodology
I check the safe vault who has same tokens and same creator, Then manually detect if they were created by the same person.

# Safe Address
0x88A253aD0be9081b6D520B91a7e620eDd6Ad5c7b

**Comment by tschubotz** [comment]
> # Reasoning
> Those Vault has same owner by 0x8CA6fb6A34dA6B5f486f977c5E1c7eB021233625 . And same creator from 0x2A1049062c6Cfd69bd38fbaf3b0559DF1DBbc92c 0x02CA4101eA84f400c62b3BeB87Fb5450a8702941

Creating several Safes with the same owner/creator is not airdrop farming per se but quite common.

Please elaborate on why you think this is airdrop farming and how you can be sure to not eliminate legitimate usage.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
