### ISSUE TITLE
Addresses without any tx history

### ISSUE THREAD

**Issue by wjw12** [safe-global/safe-user-allocation-reports#243]
# Related Safe Addresses

```
0x112efae30e371e43ff9719965048bff70f519e1c
0x2db6320c647fe6af6ef096523387e43efc7ebe35
0x45c3e85c6586501883141f7e33165cd5d19a9c9a
0x45fc0f37fed5a45ee35287abb8ab95f33c7a51ed
0x4990a1ba078ac31eb955b1285516bc4e391f0e5e
0x6b00e0465b7f2c45a0160d9ba1e301182caf2c26
0x88e79af0c051a0cd0dda7138f647e0377c907e61
0x8a368801a9a08a6e979978c6b831befa7b30f0ad
0x8dfd1f84cf9d29b4aaf6b2baf1c509164f73473e
0xbee4eaef515072c41b23cbe937d48d8207de2e32

```

# Reasoning

These addresses do not have any tx history in etherscan. Was it caused by a glitch when compiling the airdrop list?

Example:

https://etherscan.io/address/0xbee4eaef515072c41b23cbe937d48d8207de2e32

https://etherscan.io/address/0x2db6320c647fe6af6ef096523387e43efc7ebe35

![image](https://user-images.githubusercontent.com/8369203/189323261-04f3258e-c5e7-4797-a26e-f7b5938753c3.png)

# Methodology

The reported addressed are identified by manual checking against Etherscan. Since there are only 10 of them, it didn't take me much effort to verify them all by hand.

# Safe Address

0x984129b1C8D6048DF516D81f730475AF7D0E4223

**Comment by wjw12** [comment]
I was wrong!
They did have ERC20 tx history, and all look like this

examples:
![image](https://user-images.githubusercontent.com/8369203/189435540-86b08ec8-ddfa-4572-af13-2ce962d8aa20.png)

https://etherscan.io/address/0x2db6320c647fe6af6ef096523387e43efc7ebe35#tokentxns

https://etherscan.io/address/0xbee4eaef515072c41b23cbe937d48d8207de2e32#tokentxns

It transferred out 25 "Opyn ETH Put" tokens to DXdao: Mesa wallet, and later received 25 "Opyn ETH Put" tokens again. Such behavior is repetitive. All happened on May-20-2020 UTC

Maybe there were using Safes to farm Opyn airdrop

**Comment by skydotone** [comment]
@tschubotz
Why don't you check my issue?
I have spent a lot of time, experience, to present the most concise way, you skip!

**You don't even reply to me!!!**

**Comment by tschubotz** [comment]
Since Safe txs are internal txs, they might not appear on etherscan.
Check e.g. 
https://gnosis-safe.io/app/eth:0x112efae30e371e43ff9719965048bff70f519e1c/transactions/history
https://gnosis-safe.io/app/eth:0x2db6320c647fe6af6ef096523387e43efc7ebe35/transactions/history
https://gnosis-safe.io/app/eth:0x45fc0f37fed5a45ee35287abb8ab95f33c7a51ed/transactions/history

They all made txs.
The txs look quite similar, afaik they are related to an earlier feature of Gnosis Protocol v1 ("Mesa") and are legitimate use.

cf. https://dune.com/queries/1034933
