### ISSUE TITLE
has same owner from 0x7fE0A22629eCD75cec5E9427dEC9F26C4Beb49dD

### ISSUE THREAD

**Issue by ExRui** [safe-global/safe-user-allocation-reports#245]
# Related Safe Addresses

```
0xb4c93d4d2de01d8fca2425fae703068792cd5b16
0xf53b40dc9c2da0a9198d3cfe8a845c9fff3cd3b7
0x0eed91e8b96b9c7b8dca4c525eceeea974070c81
0x261b183938664935f65ff91a9d74f87c4b2c0513
0x4f8bf87be6950c1728685899fadbb74cbbc4334c
0x67380b7bbcaa81ef47a13434c0092739fc0e0bcb
0xd0e04fa0ef76aaaa8f3e46a5dabb8ea90531648f
0xf34a75475b6b69637709a66c6eeb94613f69b8e8
0xbf6b8d52a39efe4fccc1a6605f8279a29b1a5aaa
0x0d0ba2fb3c3cd012f68e6d1023c2c33d03100d7e
```
# Reasoning
Those Vault has same owner by 0x7fE0A22629eCD75cec5E9427dEC9F26C4Beb49dD .
And same creator from 0x7fE0A22629eCD75cec5E9427dEC9F26C4Beb49dD 0xe26650d1146A544e68077b2cBDf40bB3574c2634

# Methodology
Excel to get same owner or creator, Then manually detect if they were created by the same person.

# Safe Address
0x88A253aD0be9081b6D520B91a7e620eDd6Ad5c7b

**Comment by tschubotz** [comment]
> # Reasoning
> Those Vault has same owner by 0x7fE0A22629eCD75cec5E9427dEC9F26C4Beb49dD . And same creator from 0x7fE0A22629eCD75cec5E9427dEC9F26C4Beb49dD 0xe26650d1146A544e68077b2cBDf40bB3574c2634

Creating several Safes with the same owner/creator is not airdrop farming per se but quite common.

Please elaborate on why you think this is airdrop farming and how you can be sure to not eliminate legitimate usage.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
