### ISSUE TITLE
He created 10 wallet addresses, and these 10 wallet addresses were airdropped!!

### ISSUE THREAD

**Issue by qlmessi10** [safe-global/safe-user-allocation-reports#25]
<img width="960" alt="屏幕截图 2022-09-08 232417" src="https://user-images.githubusercontent.com/77811636/189162736-ed737594-6e4e-4dca-8b56-eb7f623264a4.png">
Querying an address through the Ethereum browser has created 10 multi-signature addresses, and all of them have transactions. The query link is:https://etherscan.io/txs?a=0x1ee199c1832d4cfd075ad2708feb75fc8c80b8c6&p=1
eth address:
0x1ee199c1832d4cfd075ad2708feb75fc8c80b8c6
Relevant safe address:0x9aDB2404Af11Ed004B9bCcF8bb6cEBA11833E6c0
0xEaCae0A7004C3466ee1C86aFFB08b738e6B11a2f
0xA123ee02e6673C2Ef0A7bfBde35956804EE6fc12
0x8c22A00a94F1FbB870ab65E4a30530Eb253Bc1fa
0x2fd8fff98f6fEa01d1d4E33262a6a9C70e4697Bd
0xa159AFEc31851B754AECA1be5c914eaA2eEf31a8
0x7524fbBB8a654eDe614dDec64Bf809240016Af27
0xA549cA95fBd5785d56029029d6D93Ad8D716e1dD
0x1413fbdee7f7547d8e35cAFAFde97Cf8aeEB59C8
0x2e016964119fCfb4F77Bee3A057152dBA9F89E9a

My Safe Address：eth:0xab31c9A6504b82ec0B1021a8b294eBE04D3bFB4e

**Comment by tschubotz** [comment]
Please elaborate on why these are safes created for airdrop farming. Just the fact that 1 addresses created all of them doesn't qualify.
If e.g. a wallet uses a relayer to create Safes, the relayer would be the account that created all user Safes which is not airdrop farming per se.

Also this report is of very low quality and hard to read. Please use the provided issue template.

**Comment by qlmessi10** [comment]
Please check here
https://github.com/safe-global/safe-user-allocation-reports/issues/66

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
