### ISSUE TITLE
Airdrop hunter address, one person and one address created 56 multi-signatures

### ISSUE THREAD

**Issue by yt00131** [safe-global/safe-user-allocation-reports#3]
0x3437977766fe4e39d5ade5206470ae9aef15f7ac
0xC6dB09a301Bfb0991458074199a905245f13d043
0x4a8c28b424bbd58799b766edeced5b29f86cf8ff
0xa0C33d89C9F8782275B4302f0B37818dF4aCC506
0xa8246172595716Fa28D62e0e5E26719A87bA67d1
0x58e940d446C0899179275B53F9eCF77e1C4c65e9
0x58e940d446C0899179275B53F9eCF77e1C4c65e9
0xC18924a3E29045b76327ac6683bBf30dF1c4Ef28
0xa75eE0366af36572C46e2b672dff918e7a624284
0x2A032E7a4575d067953fa85b02a934916b519571
0x299b68AC4725F5Be3063f4Cd33C627A3b12CdcE0
0xcB809e0951054742b1b86761d23B51A56DdaB26F

Reasoning
The airdrop hunter used the 0xca33b0edfb55c99d99b1d8f76f07ffe88036083d mainnet wallet to create 56 multi-signature addresses, and all of them received high token rewards,The query link is https://etherscan.io/address/0xca33b0edfb55c99d99b1d8f76f07ffe88036083d?method=Create__Proxy__With__Nonce~0x1688f0b9
Methodology
Querying an address through the Ethereum browser has created 56 multi-signature addresses, and all of them have transactions. The query link is https://etherscan.io/address/0xca33b0edfb55c99d99b1d8f76f07ffe88036083d?method=Create__Proxy__With__Nonce~0x1688f0b9

My Safe Address
0x04b9f219331e4586Ae35cff9065eFc2A09F29751

**Comment by tschubotz** [comment]
Please elaborate on why these are safes created for airdrop farming. Just the fact that 1 addresses created all of them doesn't qualify.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...
- were created by the same address
- have the same owner
- conducted the same transactions
... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
