### ISSUE TITLE
0xfe05fae1dceafd4eab8e45fde1a87956876e8d7f

### ISSUE THREAD

**Issue by qzz0518** [safe-global/safe-user-allocation-reports#44]
## Related Safe Addresses
0xd0c70d4c4b1e931a632ed1709d1f8f9bc5736f37
0x528d8b327c32869cbee50d8a3fa7f97691452140
0x1582d1b26b3c8e6c9c503546e961ec57b6ba9638
0x4ed0b17fce840bce97307b3595fc738a113ae2c8
0xb65f45c3746107f614c2365d86fe264ab2ca24aa
0xee52349da59c55763bc5ec3c2e7cf75e31fee847
0x75141d20c19de322477954e144f834720457cbc5
0xfe103025fc043f9137f48760d37842b614f2c7f3
0x34b3701b9ea857ce2a4ab5eda586aefc0d668ab3
0x56245599befd89b88b3ab466022f2f680167dc1c

## Reasoning
These safe accounts are all created by 0xfe05fae1dceafd4eab8e45fde1a87956876e8d7f
All 10 accounts were created very close to each other ，and after the account is created, all interactions are done using Capsule Coin (CAPS) to transfer 10 tokens, and all accounts operate exactly the same

like this
https://etherscan.io/tx/0x72a125947ac1ac28d840821aa6f587edc2743d7212ef24d4337413e399a4f7a7
https://etherscan.io/tx/0x1fca46e4cf0d4d3d47acf1f41a4da13266e99c496f856ed679ffcde89332122f

## Methodology
Luabase was used for preliminary data removal, and then all TX were checked one by one by EtherScan

## My Safe Address
0xf4ed1EF1f7A52DC7Dd10a9B5d43f23748A1E8992

**Comment by tschubotz** [comment]
> These safe accounts are all created by 0xfe05fae1dceafd4eab8e45fde1a87956876e8d7f

Creating multiple Safes from 1 account is not airdrop farming per se, pls elaborate.

The first account stores >400k USDC. Safe as store of value is legit usage. https://etherscan.io/address/0xd0c70d4c4b1e931a632ed1709d1f8f9bc5736f37

> and all accounts operate exactly the same

Please elaborate on how this is airdrop farming an how exactly they operate.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
