### ISSUE TITLE
Safe Airdrop Farmers by @0xNetrunner

### ISSUE THREAD

**Issue by 0xnetrunner** [safe-global/safe-user-allocation-reports#470]
# Related Safe Addresses

We believe the following list of Safe addresses fall within the 'airdrop farming' category that would receive a SAFE user allocation.
[airdrop_farmers.csv](https://github.com/safe-global/safe-user-allocation-reports/files/9590838/airdrop_farmers.csv)

# Reasoning

In this report we analyze the addresses of Safe users to identify potential airdrop farmers. 

Building on [0xKARTOD's ranking system](https://github.com/safe-global/safe-user-allocation-reports/issues/442#), we used the [Red Score Data](https://dune.com/queries/1268823/2173773) to create a filter selecting addresses **created after GIP-29 and had 2 or less transactions within a given period**. We believe this has the highest probability of identifying airdrop farmers, without penalising legitimate users and testers.

# Methodology

Addresses selected from the: Safe provided file: [safe_user_allocations_reworked.csv](https://github.com/safe-global/safe-user-allocation-reports/blob/main/safe_user_allocations_reworked.csv). 0xKARTOD analytics ([Red Score Data](https://dune.com/queries/1268823/2173773)), is used to populate a data table. Using the parameters below, a filter was used to identify airdrop farmers, whilst erring on the side of caution, so as not to penalise legitimate users (relayers, scripts, power users, exchanges) and testers.

Filter:
- 2 or less transactions within a given period.
- Created after GIP-29

# Safe Address

If this report is used to filter airdrop farmers, then I would like to split the SAFE proceeds 50/50 with [@0xKARTOD](https://github.com/0xKARTOD):
0xnetrunner Safe: `0x8b548302239366cb73475fFaEde9687cC2D31371`
0xKARTOD Safe:`0x1B491d59846cb605A24a4690Df631946E52a2D0e`

**Comment by tschubotz** [comment]
Thank a lot for the report. Checking the list of Safes there seem to be quite some that rather look like legitimate usage. Just to name 3:

https://gnosis-safe.io/app/eth:0x14ab82062dc2622c4f1467042652fb7110b92d53/transactions/history
https://gnosis-safe.io/app/eth:0x5bffbb1278db2f5a5d53aefdd9656c574b599f5e/transactions/history
https://gnosis-safe.io/app/eth:0x02308b53273ab3494d482d5fb3d1f0710acb0890/transactions/history

Since you reasoning is just based on the Dune query, I'm unable to see how you can be sure this would not eliminate legitimate use.
