### ISSUE TITLE
This address created 0xd24cba893a68573755b9763f329a6f4699981339

### ISSUE THREAD

**Issue by SeanCCkaka** [safe-global/safe-user-allocation-reports#70]
0x70a9016438c8b6236260087d043a7f412cf73944

0x4d1a4b41de058512c7efe24f97d09852094e2864
0xffea55e9085a6baad3e408008a66fce89bf9de98
0x9ef4f4fc49337c40c901eb831bfc177379a0a199
0x599bd0d5df0308bb06771fb1957cb504d0d837f7

# Reasoning

This address first ETH come from the FTX. And besides the transaction with safe, it hardly have another transaction. So I can defifi the address is the airdrop farmer.
https://etherscan.io/address/0xd24cba893a68573755b9763f329a6f4699981339
# Methodology

with target as (
select *
from url('https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/safe_user_allocations_reworked.csv', CSVWithNames)
), transactions as (
select t1.*
from ethereum.transactions t1
join target t2
on t1.to_address = t2.safe_address
)

select distinct to_address
from transactions
where from_address = lower('0xD24CBa893A68573755B9763F329A6F4699981339')
Example:

# Safe Address

0xc7495E1c9A62e74473d890eaE40537713AAC73f7

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
