### ISSUE TITLE
0x7DFd7ddE044De1FFF1579e0da47e3D5aD48c38F2 by 17 addresses created

### ISSUE THREAD

**Issue by Henrryfeng** [safe-global/safe-user-allocation-reports#88]
# Related Safe Addresses

0x4d041e327b1e691daf9c621d3ca107afb7e8844e
0xabbabf9b0216b163f8a51806df8ecc8c4765289e
0x22b50afb355f5d83626fd2feb720c5bb64ebffa9
0x5b27674f81f37afd79a08f51ba23e373934e520e
0xe4527d7ce14f6f5d48871583b9f391feadc00572
0x72aca4e314911f5b73d5e38990297dfba55b1cc2
0xff96d65b803166fdb831b7ae015ff3494cad8b97
0x72ede922683dc98497317744cd9ee62345462561
0x49bcff7dd2ddea99bdfc4ef3565968fc43cf57f3
0x6424d6e2e0c87e9d537871663fe1c417d1c8a2a3
0xc32049468265aca324b56e6c1fd867dc6ad773c0
0x2050cc4e48ec7cd8ad94561a3b2df1d187ab9e3d
0x9bea44073a9b7c6ef5e211f20526dea775172957
0x43c88252e42fe8a2b88e42a6da9643c5ff25b01d
0x4fe0b6984d3d86eb450fae447990d372123eb98d
0xbed8e6497f9c94acc41daeed22aa38c73ca8f4a9
0xda6c4d202d41416ce6cbfc1f4af41cde93952dbe

# Reasoning

-->
17 addresses created
0x7DFd7ddE044De1FFF1579e0da47e3D5aD48c38F2 sends ETH and ERC20 tokens, USDT to other addresses

0x7DFd7ddE044De1FFF1579e0da47e3D5aD48c38F2
send usdt to
0x22b50AFb355F5D83626fD2feb720c5bB64EbFFa9
HASH: 0xd082b72448f754ee6ace5b45b84bd6ef6536bef89fc20278bb487c3934858045

0x7DFd7ddE044De1FFF1579e0da47e3D5aD48c38F2
SEND ETH To
0x72aca4e314911f5b73d5e38990297dfba55b1cc2

HASH: 0xa9aac8cd92bca973b8d798bc64a5c4161c5a35dc9f76563600c369cd085f6693

# Methodology
-->
with target as (
select *
from url('https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/safe_user_allocations_reworked.csv', CSVWithNames)
), transactions as (
select t1.*
from ethereum.transactions t1
join target t2
on t1.to_address = t2.safe_address
)

select distinct to_address
from transactions
where from_address = lower('0x7DFd7ddE044De1FFF1579e0da47e3D5aD48c38F2')

# Safe Address

`0x416D9bE1d9718c44Fe642098230D54De37340Bf7 `
-->

**Comment by tschubotz** [comment]
This report needs to be structured better. I'm unable to follow the reasoning.
I just checked the first address and don't see how this should be airdrop farming. Please elaborate. https://etherscan.io/address/0x4d041e327b1e691daf9c621d3ca107afb7e8844e

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
