### ISSUE TITLE
zhzhuxia.eth is airdrop farmer

### ISSUE THREAD

**Issue by SeanCCkaka** [safe-global/safe-user-allocation-reports#98]
# Related Safe Addresses

0xc76c8e9bd5a2341dd7cf5ad17ed2ccf647e102b4
0x56c2366b0f7a64d49a4ff7b04c28ddb813edc588
0x62eeefab55104bc0d1ae2ad181e2b67476e5ef47
0x38b074e474afda6967868e2b12b829dc815bf3fd
0x633b7218644b83d57d90e7299039ebab19698e9c
0xc102d2544a7029f7ba04beb133deadaa57fdf6b4
0x67575860eefc18b98c6ff2cd50f7c7684fa85676
0x386f1721fce8df5c50a6c4dfb92fad894c4eb51a
0x74cb633d1cf1a4a73f621c630a3b1b003450e5a3
0xc1d512d5e1550b196be47c5234ec566cee7c8d3
0x4e2f98c96e2d595a83afa35888c4af58ac343e44
0x44c21334524ed8ade10d18a2e3b1636c60f0289b
0x47ba9203e1d8cd5b25a063329ae88a6755a6e0bc
0xc7768a53234a72b53a980c977eb07c8c8f5e76a1
0x9626b7fa440e8c7001b72aac31a9e47150e58d8c
0xe452420eede6a8075470a5decd40ef3e1f6d2493
0xfa002b29130bdb1f464473e7c524c1c287f1c969

</body>
</html>

# Reasoning

He has the ENS service. And he has the transaction history with zaima.eth(another airdrop farmer), and his ETH come from the FTX.
He own many ERC-20 token, and many token transacted from the gate.io. He also created the sudoswap pool. Above all the address hold by a normal user. A airdrop famer.

https://etherscan.io/address/0xD81152389720712E74FaBb14C12a4A14BdB6869d

# Methodology

with target as (
select *
from url('https://raw.githubusercontent.com/safe-global/safe-user-allocation-reports/main/safe_user_allocations_reworked.csv', CSVWithNames)
), transactions as (
select t1.*
from ethereum.transactions t1
join target t2
on t1.to_address = t2.safe_address
)

select distinct to_address
from transactions
where from_address = lower('0xD81152389720712E74FaBb14C12a4A14BdB6869d')

# Safe Address
0xc7495E1c9A62e74473d890eaE40537713AAC73f7

**Comment by tschubotz** [comment]
> He has the ENS service. And he has the transaction history with zaima.eth(another airdrop farmer), and his ETH come from the FTX.
> He own many ERC-20 token, and many token transacted from the gate.io. He also created the sudoswap pool. Above all the address hold by a normal user. A airdrop famer.

This is incomprehensible. Please provide a higher quality report and elaborate on how this is airdrop farming.

**Comment by lukasschor** [comment]
We haven't received any further information on this ticket and therefore deemed this submission invalid.

Unfortunately just the pure fact that Safes...

- were created by the same address
- have the same owner
- conducted the same transactions
- received assets from the same address

... is not enough reasoning for a valid submission, as there are legit user behaviour leading to such as well (relayer, scripts, power users, exchanges)

This submission didn't provide sufficient indicators to convince the team that there is some targeted airdrop farming behind the provided addresses. As per the rules, when in doubt we will default in favor of the airdrop recipients in order to not risk any false positives when sorting out airdrop hunters.
